# Dockerfile.nodejs
FROM node:22

# Set working directory inside the container
WORKDIR /Node

# Copy package.json and package-lock.json from the Node directory in the build context to the container
COPY Node/package*.json .

# Install dependencies
RUN npm install

# Copy the rest of the application code from the Node directory
COPY Node/ .

# Expose the port the app runs on
EXPOSE 3000

# Command to run the application  
CMD ["npm", "start"]
